### ISSUE TITLE
test thingi

### ISSUE THREAD

**Issue by GabrielREPersson** [JFxMachina/MDCode#10]
this is a test issue that i write in hopes of being able to convert it to a card in the project screen

Edit: it turns out that i can not :(

**Comment by GabrielREPersson** [comment]
is this a comment
![image](https://user-images.githubusercontent.com/90193773/143587881-a214b247-74a4-46fe-b246-5df8dffe1f56.png)

**Comment by JFxMachina** [comment]
The automation should be in place, but clearly it isn't working

**Comment by mehDN** [comment]
comment

**Comment by JFxMachina** [comment]
nc
